### ISSUE TITLE
demo能查到列表，但是无法获取docid

### ISSUE THREAD

**Issue by Salandia** [Henryhaohao/Wenshu_Spider#7]
docid = self.js_2.call('getdocid', runeval, casewenshuid)，每次执行到这一句就没有结果了

**Comment by Henryhaohao** [comment]
你好:
你可以参考issues1 :get_docid.js调用错误 [https://github.com/Henryhaohao/Wenshu_Spider/issues/1](url)
感谢支持~!:heart: @Salandia

**Comment by Salandia** [comment]
谢谢，nodejs换了8.11.3好了
